stop_words = [
    'algorithm',
    'approach',
    'based',
    'data',
    'dataset',
    'datesets',
    'deep learning',
    'deep',
    'feature',
    'learning',
    'machine',
    'method',
    'methods',
    'model',
    'models',
    'network',
    'networks',
    'neural network',
    'neural',
    'paper',
    'performance',
    'problem',
    'propose',
    'proposed',
    'result',
    'results',
    'show',
    'state',
    'task',
    'tasks', 
    'training',
    'using',
    'work',   
]